#####  DO NOT EDIT THIS FILE  #####
#####  DO NOT EDIT THIS FILE  #####
#####  DO NOT EDIT THIS FILE  #####
#####  DO NOT EDIT THIS FILE  #####
#####  DO NOT EDIT THIS FILE  #####

### CMS 330 automated testing program, ver. 1.0
### DSM, 2017

from os import system
from os import listdir
import sys
from sys import exit

# List of executable files
programs = ['basic', 'optional']

# Lists of tests in the tests/ directory associated with each program
tests = {'basic':['basic_if_1', 'basic_if_2', 'basic_nested_if',
                  'basic_parse_error_1', 'basic_parse_error_2',
                  'basic_while_1', 'basic_while_2', 'basic_nested_while',
                  'basic_list_primes', 'basic_square_root'],
         'optional':['optional_for_1', 'optional_for_2', 'optional_string_1',
                     'optional_real_1', 'optional_real_2',
                     'optional_sub_1', 'optional_sub_2', 'optional_sub_3']
}

test_file_list = listdir('./Tests')

basic_passed = 0
optional_passed = 0
final_return_code = 0

# Remove existing executables
print '\n#####  Removing any existing class files  #####'
system('rm *.class')

# Build the project
print '\n#####  Compiling with javac  #####'
rc = system('javac *.java')
if rc != 0:
	print 'Build failed. Exiting.'
	exit(1)

# A working build is one of the tests
print '\nBuild passed.',
basic_passed += 1

for program in programs:

	print '\n\n#####  Testing %s  #####' % program

	for test in tests[program]:
		print '\n##  Test %s  ##' % test
		out_file = test + '.out'
		in_file = './Tests/' + test + '.y'
		cmp_file = './Tests/' + test + '.cmp'

		run_command = 'java Driver %s > %s' % (in_file, out_file)

		# diff compares two files and reports if they are different
		# -Z ignores trailing whitespace
		# -q gives same/different reporting
		diff_cmd = 'diff -Z -q %s %s' % (out_file, cmp_file)

		system(run_command)
		rc = system(diff_cmd)

		if rc == 0:
			print 'Passed.'

			if program == 'basic':
				basic_passed += 1
			else:
				optional_passed += 1
		else:
			final_return_code = 1  # Return 1 if any tests fail

		print '\nYour program\'s output:'
		system('cat %s' % out_file)
		print '\nExpected output:'
		system('cat %s' % cmp_file)

print '\n\n#####  Final Score  #####'
num_tests = sum([len(x) for x in tests.values()]) + 1
print 'You passed %d out of %d required tests.' % (basic_passed,  11)
print 'Percentage = %f' % (float(basic_passed) / 11 * 100)

print 'You passed %d out of %d optional tests.' % (optional_passed,  8)
print 'Extra points = %f' % (float(optional_passed) / 8 * 50)

# Clean up
system('rm *.out')

exit(final_return_code)